apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto-conf: |
    log_dest std_out
    log_type all
    log_timestamp true
    listener 9001
# name of file | with contents inside the file 

